### PR TITLE
[MEAR-271] added support for <resourceRef> <lookup-name> property

### PR DESCRIPTION
**Pull request by fabio-boldrini**
NO JIRA Issue

[MEAR-271] add support for **lookup-name** tag inside **resourceRef**

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

### CODE REVIEW

**Comment by mabrarov** [comment]
Does anybody know what is the plan for this pull request? [MEAR-271](https://issues.apache.org/jira/browse/MEAR-271) JIRA issue is closed but this pull request is not merged and last commit is done a year ago.

**Comment by khmarbaise** [comment]
I simply missed to close this PR here on Github. If you take a look into the code 
https://gitbox.apache.org/repos/asf?p=maven-ear-plugin.git;a=commitdiff;h=f002918d6cad2e607572a5049fe2b8e078a04979 you see two things the pr with the code and author ship has been taken and has been integrated into a release.

The last commits on [maven-ear-pugin](https://github.com/apache/maven-ear-plugin/commits/master) have been done two weeks ago ...

**Comment by mabrarov** [comment]
@khmarbaise, do you know any plans about release of Maven EAR Plugin 3.0.2? I need this fix for enforcement of initialization order b/w resources provided by Java EE container and applications deployed into that container. Refer to [WFLY-944](https://issues.jboss.org/browse/WFLY-944) for details.

**Comment by jira-importer** [comment]
Resolve #456

**Pull request closed without merging**
