### PR TITLE
[MEAR-304] Update plugin dependencies

### PR DESCRIPTION
**Pull request by cstamas**
Set maven bits to proper scope, update
deps and fix parent enforcer that still
want to use maven2 bits.

---

https://issues.apache.org/jira/browse/MEAR-304

### CODE REVIEW

**Comment by michael-o** [comment]
@cstamas Can you rework this for Maven 3.2.5? I would then finalize the release.

**Comment by cstamas** [comment]
Would be nice to have here m-rar-p release, as latest is 2.x and is used in tests...

**Comment by cstamas** [comment]
Updated to Maven 3.2.5 and ITs are passing OK

**Comment by slawekjaranowski** [comment]
@cstamas looks ok - can you finish?

**Comment by slawekjaranowski** [comment]
Suppressed by #73 and other

**Comment by jira-importer** [comment]
Resolve #182

**Comment by jira-importer** [comment]
Resolve #182

**Pull request closed without merging**
