### PR TITLE
[MEAR-322] Try to reproduce issue

### PR DESCRIPTION
**Pull request by slawekjaranowski**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [ ] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MEAR) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [ ] Each commit in the pull request should have a meaningful subject line and body.
 - [ ] Format the pull request title like `[MEAR-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MEAR-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [ ] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [ ] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by pzygielo** [comment]
Hi @slawekjaranowski, thanks for checking this issue.

Currently I have bisected it to 07a84983809b4ec416b1330412bbd83844a88a44.

I have _"reproducer"_ but it is with non-public full project so far. I will try to reduce it to the publishable minimum.

Also - I have problems to reproduce it locally on regular linux box. It fails only on GitHub Actions node. Might be connected with the container file system (I'm not very familiar with such details).

**Comment by slawekjaranowski** [comment]
> Hi @slawekjaranowski, thanks for checking this issue.
> 
> Currently I have bisected it to [07a8498](https://github.com/apache/maven-ear-plugin/commit/07a84983809b4ec416b1330412bbd83844a88a44).
> 
> I have _"reproducer"_ but it is with non-public full project so far. I will try to reduce it to the publishable minimum.
> 
> Also - I have problems to reproduce it locally on regular linux box. It fails only on GitHub Actions node. Might be connected with the container file system (I'm not very familiar with such details).

can be connected with JDK versions and build

**Comment by pzygielo** [comment]
> Also - I have problems to reproduce it locally on regular linux box. It fails only on GitHub Actions node.

To clarify:
I have problem **to build** reproducible archive locally.
Archive produced in GH Action is bad, and fails to deploy locally in the same way as in GH Action.

**Comment by pzygielo** [comment]
> can be connected with JDK versions and build

Using the same JDK (Temurin 11.0.16.1) here and there.

**Comment by pzygielo** [comment]
I have tested m-ear-p:3.3.0 + revert 07a84983809b4ec416b1330412bbd83844a88a44 and it's also fine and does not cause the deploy problem.

**Comment by slawekjaranowski** [comment]
In 07a84983809b4ec416b1330412bbd83844a88a44 I was replaced a way how items are changed in attached modules
before it whole module was unpacked to temporary location, one file META-INF/MANIFEST.MF was updated and some of items was removed with skiny from libs dirs ...
Finally whole module was pack again.

In new way `ZipFileSystem` is used to do needed changes in archive without repacking ...

I will can verify deployments in my work in works days with STORE options.

Maybe it is related: https://bugs.openjdk.org/browse/JDK-8143613

**Comment by pzygielo** [comment]
One module that gets repacked, instead being taken as-is, differs in following way for several entries, here just shown for MANIFEST.MF:

\- is entry from original module (jar) as produced during build
\+ is entry from m-ear-p modified file (from ear-module/target/ear dir)

```diff
@@ -1,16 +1,25 @@
 0027 LOCAL HEADER #2       04034B50
 002B Extract Zip Spec      0A '1.0'
 002C Extract OS            00 'MS-DOS'
-002D General Purpose Flag  0800
+002D General Purpose Flag  0808
+     [Bit  3]              1 'Streamed'
      [Bit 11]              1 'Language Encoding'
 002F Compression Method    0000 'Stored'
 0031 Last Mod Time         5556B810 'Sat Oct 22 23:00:32 2022'
-0035 CRC                   7928FEFC
-0039 Compressed Length     00000051
-003D Uncompressed Length   00000051
+0035 CRC                   00000000
+0039 Compressed Length     00000000
+003D Uncompressed Length   00000000
 0041 Filename Length       0014
-0043 Extra Length          0000
+0043 Extra Length          0009
 0045 Filename              'META-INF/MANIFEST.MF'
-0059 PAYLOAD               Manifest-Version: 1.0..Created-By: Maven
-                           JAR Plugin 3.3.0..Build-Jdk-Spec: 11....
+0059 Extra ID #0001        5455 'UT: Extended Timestamp'
+005B   Length              0005
+005D   Flags               '01 mod'
+005E   Mod Time            635459F0 'Sat Oct 22 23:00:32 2022'
+0062 PAYLOAD
+
+020A STREAMING DATA HEADER 08074B50
+020E CRC                   005ED761
+0212 Compressed Length     000001A8
+0216 Uncompressed Length   000001A8
```

As in linked [JDK-8143613](https://bugs.openjdk.org/browse/JDK-8143613) - it's indeed Bit 3 of GPF...

**Comment by jira-importer** [comment]
Resolve #197

**Pull request closed without merging**
