### PR TITLE
[MEAR-329] Support JakartaEE 11 schema

### PR DESCRIPTION
**Pull request by pzygielo**

### CODE REVIEW

**Comment by pzygielo** [comment]
Locally I was also getting failures when running against 21 (and it was all fine for 17).
```
Unsupported class file major version 65
```

- I've not tracked when building with 21 was introduced, but it was there: https://github.com/apache/maven-ear-plugin/pull/107 at least.

**Comment by pzygielo** [comment]
Using m-invoker-p, newer than inherited from parent (e.g. 3.8.0) helps (but not for `descriptor-encoding`, due to `XMLParser` missing - for it was in groovy-all, and is missing in plain groovy artifact).

But it's not in scope of this PR I think.

**Comment by slawekjaranowski** [comment]
> Using m-invoker-p, newer than inherited from parent (e.g. 3.8.0) helps (but not for `descriptor-encoding`, due to `XMLParser` missing - for it was in groovy-all, and is missing in plain groovy artifact).
> 
> But it's not in scope of this PR I think.

Right  - first we should upgrade parent pom.

**Comment by pzygielo** [comment]
> Right - first we should upgrade parent pom.

I see some effort for that
- #97
- eafbdeeb69babfae2454f10dc7047affb024ba12

but it take ages to move forward :disappointed:

**Comment by pzygielo** [comment]
Rebased, and I'm happy to say that locally with Java 21 I'm getting now:
```
[INFO] Results:
[INFO] 
[INFO] Tests run: 102, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] 
[INFO] --- invoker:3.7.0:verify (integration-test) @ maven-ear-plugin ---
[INFO] -------------------------------------------------
[INFO] Build Summary:
[INFO]   Passed: 18, Failed: 0, Errors: 0, Skipped: 0
[INFO] -------------------------------------------------
[INFO] 
[INFO] --- failsafe:3.3.0:verify (default) @ maven-ear-plugin ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
```

**Review by slachiewicz — APPROVED** [review]

**Comment by pzygielo** [comment]
Can this be merged, please?

**Comment by jira-importer** [comment]
Resolve #204

**Comment by jira-importer** [comment]
Resolve #204

**Comment by pzygielo** [comment]
Can this be released, please?

**Pull request merged**
