### PR TITLE
[MEAR-273] - [eclipse] - Adding extra slash causing issues for eclipse editors

### PR DESCRIPTION
**Pull request by lak-proddev**
Following this checklist to help us incorporate your 
contribution quickly and easily:

 - [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MEAR) filed 
       for the change (usually before you start working on it).  Trivial changes like typos do not 
       require a JIRA issue.  Your pull request should address just this issue, without 
       pulling in other changes.
 - [x] Each commit in the pull request should have a meaningful subject line and body.
 - [x] Format the pull request title like `[MEAR-XXX] - Fixes bug in ApproximateQuantiles`,
       where you replace `MEAR-XXX` with the appropriate JIRA issue. Best practice
       is to use the JIRA issue title in the pull request title and in the first line of the 
       commit message.
 - [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
 - [ ] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will 
       be performed on your pull request automatically.
 - [ ] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure
please ask on the developers list.

To make clear that you license your contribution under 
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

 - [x] I hereby declare this contribution to be licenced under the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)

 - [ ] In any other case, please file an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by lak-proddev** [comment]
Is there any reason  to adding extra slash "/" for javaee8 schema location.
Actually, this is causes  issues in eclipse side.

>         writer.addAttribute( "xsi:schemaLocation",
>                              "http://xmlns.jcp.org/xml/ns/javaee http://xmlns.jcp.org/xml/ns/javaee/application_8.xsd" );
>

**Comment by khmarbaise** [comment]
There seemed to be no reason. And it looks like you are right cause the other entries do not contain a slash like this...

**Comment by khmarbaise** [comment]
Added your commit to branch. Had to change the commit message to follow our guidelines..and lets see what CI says...

**Comment by khmarbaise** [comment]
Ci has said Ok and I merged it into master. Thanks for your contribution.

**Comment by lak-proddev** [comment]
khmarbaise, Thanks for merging. When  can I expect next release ?

**Comment by jira-importer** [comment]
Resolve #440

**Comment by jira-importer** [comment]
Resolve #440

**Pull request closed without merging**
