### PR TITLE
[MEAR-182] skipClassPathModification in case of undefined Class-Path entry of MANFIEST.mf

### PR DESCRIPTION
**Pull request by mabrarov**
[MEAR-182] - Don't add MANFIEST.mf `Class-Path` entry for EAR module if `skipClassPathModification` is `true` and original MANFIEST.mf of the EAR module artifact doesn't contain `Class-Path` entry. Refer to [that comment](https://issues.apache.org/jira/browse/MEAR-182?focusedCommentId=17244796&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17244796) in MEAR-182 for description of the bug which this pull request fixes.

### CODE REVIEW

**Comment by mabrarov** [comment]
@hboutemy, it would be nice to include this PR and PR #22 into 3.2.0 release of Maven EAR Plugin.

**Comment by hboutemy** [comment]
MEAR-182 https://issues.apache.org/jira/browse/MEAR-182 is an old issue closed for release 2.10
please create a new issue (we'll link it to MEAR-182), and update the commit (with rebasing, please, to have a simpler Git history)

**Comment by mabrarov** [comment]
Declining in favor of pull request #29 with fixed source branch name.

**Comment by jira-importer** [comment]
Resolve #359

**Pull request closed without merging**
