### PR TITLE
[MEAR-327] update to parent pom 39

### PR DESCRIPTION
**Pull request by elharo**
40 breaks integration tests, so take this one step at a time.

### CODE REVIEW

**Comment by slachiewicz** [comment]
Separate commit for version upgrade and then 2nd with reformat so we can add it to ignored

**Review by slachiewicz — COMMENTED** [review]
Looks like a new line type issue. I see the full file changes

**Comment by elharo** [comment]
That would mean there's a commit that doesn't build.

**Comment by slachiewicz** [comment]
Yes. That's how we do in all repos

**Comment by slachiewicz** [comment]
You have duplicate license headers

**Comment by slachiewicz** [comment]
Superseded by #119

**Comment by jira-importer** [comment]
Resolve #205

**Comment by jira-importer** [comment]
Resolve #205

**Pull request closed without merging**
