### PR TITLE
[MEAR-216] Handling test JARs as regular JARs

### PR DESCRIPTION
**Pull request by mabrarov**
* [MEAR-216] - Handling test JARs as regular JARs
* [MEAR-216] - Support of jboss-sar, jboss-har and jboss-par types of artifacts.

### CODE REVIEW

**Comment by mabrarov** [comment]
@elharo, could you please trigger Jenkins build for this pull request?

**Comment by elharo** [comment]
https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven-ear-plugin/job/mear-216/

**Comment by mabrarov** [comment]
It looks like Jenkins build passed successfully. What needs to be done to merge this pull request and close MEAR-216?

**Comment by mabrarov** [comment]
Need to check one more case I found recently. The case (I'll add a test for it) may demonstrate that this pull request is wrong and needs further work. Please, don't merge this pull request until I reply with result of my check.

**Comment by mabrarov** [comment]
I fixed [that issue](https://github.com/apache/maven-ear-plugin/pull/22#issuecomment-714485368) and this pull request is ready for review now.

@elharo and @hboutemy, your help with Jenkins build, review and merging is appreciated.

Thank you.

**Comment by mabrarov** [comment]
Merged conflicts were resolved. Please trigger a new Jenkins build.

**Review by elharo — COMMENTED** [review]
running in https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven-ear-plugin/job/mear-216/

**Comment by mabrarov** [comment]
This PR was successfully built by Jenkins. Is it possible to get this PR merged?

**Comment by mabrarov** [comment]
@elharo and @hboutemy, is it possible to get this PR merged? What's missing / pending or blocking this PR?

**Comment by hboutemy** [comment]
you're right, merged
thank you

**Pull request merged**
