### PR TITLE
[MEAR-302] Support JakartaEE 9 schema

### PR DESCRIPTION
**Pull request by pzygielo**
Locally:
```
[INFO] Tests run: 98, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 502.266 s - in org.apache.maven.plugins.ear.it.EarMojoIT
```

### CODE REVIEW

**Comment by slawekjaranowski** [comment]
please add test to EarMojoIT

**Comment by slawekjaranowski** [comment]
something like src/test/resources/projects/project-082

**Comment by slawekjaranowski** [comment]
please also rebase with the latest master codebase 😄

**Comment by pzygielo** [comment]
@slawekjaranowski - `EarMojoIT` updated with new test as suggested, changes rebased on current master.

**Review by slawekjaranowski — APPROVED** [review]

**Review by slachiewicz — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #207

**Pull request merged**
